### ISSUE TITLE
端口跳跃--无法运行

### ISSUE THREAD

**Issue by isaac574** [chika0801/hysteria-install#1]
![112233](https://user-images.githubusercontent.com/59785107/234738802-84356c36-619d-40d5-8494-559ea7750af3.jpg)

以上是VPS--UBUNTU 20.04上运行以下代码后的显示：
iptables -t nat -A PREROUTING -i eth0 -p udp --dport 16387:16485 -j DNAT --to-destination :16385
netfilter-persistent save

但客户端A)WIN7 B)LINUX DEEPLIN平台均无法联通VPS；
无法自行解决；

单端口可以联通VPS;

**Comment by chika0801** [comment]
我找了一个VPS，DD成ubuntu 20.04，按我的指南装了，客户端也是只能用16385连通服务端。换其它如 16400都连不通。

我不清楚原因。时间太久我现在也忘记当时测ubuntu是成还是没成了。

我又把系统DD成了debian11测试了是正常的。建议你要用，就用Debian11系统吧。
