### ISSUE TITLE
server log DEBUG

### ISSUE THREAD

**Issue by ggrreeeedd** [chika0801/hysteria-install#4]
可以正常使用，server log:
 DEBUG   TCP request     {"addr": ".....", "id": "user", "reqAddr": "......."}
 DEBUG   TCP closed      {"addr": ".....", "id": "user", "reqAddr": "......."}

**Comment by chika0801** [comment]
https://github.com/chika0801/hysteria-install/blob/main/hysteria.service#L9

你要改成info的话，在这里改
