### ISSUE TITLE
求助大佬

### ISSUE THREAD

**Issue by tgssaa** [chika0801/hysteria-install#5]
请问大佬：
1、hysteria2升级到2.0.1了，我该如何操作也能够升级？
2、按照大佬脚本安装到ARM小鸡上，只需将curl -Lo /root/hysteria https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64 && chmod +x /root/hysteria && mv -f /root/hysteria /usr/local/bin
修改成curl -Lo /root/hysteria https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-arm64 && chmod +x /root/hysteria && mv -f /root/hysteria /usr/local/bin吗？
还需要修改什么吗？

非常感谢大佬！！！

**Comment by chika0801** [comment]
> hysteria2升级到2.0.1了，我该如何操作也能够升级？

你去它的发布页 https://github.com/apernet/hysteria/releases 下载文件名为 `hysteria-linux-arm64` 的文件，就是服务端用的。windows端的同样下载。通过替换文件的办法，来达到升级的目的。记得替换完后要重启程序了才生效。


> 2、按照大佬脚本安装到ARM小鸡上，只需将curl -Lo /root/hysteria > > https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-amd64 && chmod +x /root/hysteria && mv -f /root/hysteria /usr/local/bin
> 修改成curl -Lo /root/hysteria https://github.com/apernet/hysteria/releases/latest/download/hysteria-linux-arm64 && chmod > +x /root/hysteria && mv -f /root/hysteria /usr/local/bin吗？
> 还需要修改什么吗？

是的，这一步就改那个文件名，下到VPS上的就是arm64版本的文件了。后面的步骤都一样。

**Comment by tgssaa** [comment]
非常感谢大佬的指点！
