### ISSUE TITLE
还是不能传输http3的数据，开了tun模式

### ISSUE THREAD

**Issue by ghost** [chika0801/hysteria-install#6]
还是不能传输http3的数据，开了tun模式，我测试用的是YouTube视频测试的，显示http1.1

**Comment by chika0801** [comment]
https://github.com/chika0801/hysteria-install/blob/main/config_server.yaml#L19

如果你用的这个服务端配置，这行帮你拒绝了，建议你也不要开，没什么好处

**Comment by ghost** [comment]
他不能传输ICMP流量吗？

**Comment by chika0801** [comment]
你要代理icmp ，是取决于你客户端用的什么形式，比如你windows用sing-box开tun（透明代理环境），就能

你win上只用hy开了scoks端口，浏览器用socks进hy，就不能，这样

**Comment by ghost** [comment]
它这个传输UDP的数据速度快不快，能比wireguard和openvpn的UDP模式快吗？

**Comment by ghost** [comment]
另外它伪装网站是指的流量显示的是伪装网站的域名吗还是

**Comment by ghost** [comment]
ok了可以传输http3了，但是icmp还是不能代理，ping是这样的
正在 Ping 1.1.1.1 具有 32 字节的数据:
来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64
来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64
来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64
来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64

**Comment by ghost** [comment]
还有这个没有IPV6地址，请问怎么开启，可以让它默认开启V6并且V6优先吗，因为v4的地址都是广播地址会导致CDN解析到很远的服务器，以及IP不干净，V6不会这样

**Comment by chika0801** [comment]
> 它这个传输UDP的数据速度快不快，能比wireguard和openvpn的UDP模式快吗？

建议去hy的tg群问作者

**Comment by chika0801** [comment]
> 另外它伪装网站是指的流量显示的是伪装网站的域名吗还是

这个也是建议同上

**Comment by chika0801** [comment]
> ok了可以传输http3了，但是icmp还是不能代理，ping是这样的 正在 Ping 1.1.1.1 具有 32 字节的数据: 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64

你不说你的环境，帮不上你了

**Comment by chika0801** [comment]
> 还有这个没有IPV6地址，请问怎么开启，可以让它默认开启V6并且V6优先吗，因为v4的地址都是广播地址会导致CDN解析到很远的服务器，以及IP不干净，V6不会这样

文档中这段

关于 direct 出站
direct 出站规则有一些额外的选项，可以用来定制其行为：

注意： bindIPv4、bindIPv6 和 bindDevice 三者是互斥的。可以只指定 bindIPv4 和/或 bindIPv6，或者只使用 bindDevice。

参考下面的加法
outbounds:
  - name: hoho
    type: direct
    direct:
      mode: 64

支持的 mode 值包括：

auto：默认值。双栈模式。客户端会同时尝试使用 IPv4 和 IPv6 地址连接目标，选择第一个成功的。
64：优先使用 IPv6，如果没有可用的 IPv6 地址，使用 IPv4。

**Comment by ghost** [comment]
> > ok了可以传输http3了，但是icmp还是不能代理，ping是这样的 正在 Ping 1.1.1.1 具有 32 字节的数据: 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64 来自 1.1.1.1 的回复: 字节=32 时间<1ms TTL=64
> 
> 你不说你的环境，帮不上你了

我是Windows11系统，Nekobox客户端，sing-box核心，tun模式，服务器是debian12.2

**Comment by ghost** [comment]
建议修改服务器配置文件默认开启UDP和IPV6优先

**Comment by ghost** [comment]
这是我的配置文件，还是没有V6



listen: :443

tls:
  cert: /root/fullchain.cer
  key: /root/private.key

auth:
  type: password
  password: 00000

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s
outbounds:
  - name: hoho
    type: direct
    direct:
      mode: 64

**Comment by ghost** [comment]
有了，谢谢，原来这个客户端里还得开一下tunv6模式

**Comment by ghost** [comment]
不过我还有一个问题，IPV6解决了，但是好像没有IPV6的DNS服务器，如何添加，格式是什么，我看官方配置文件也没有ipv6dns服务器的示例

**Comment by chika0801** [comment]
> 我是Windows11系统，Nekobox客户端，sing-box核心，tun模式，服务器是debian12.2

建议你去nekobox的tg群问下

**Comment by ghost** [comment]
> > 我是Windows11系统，Nekobox客户端，sing-box核心，tun模式，服务器是debian12.2
> 
> 建议你去nekobox的tg群问下

我在客户端的github提问了，我没有tg号，收不到验证码

**Comment by ghost** [comment]
而且tg号不安全，好像可以反查手机号

**Comment by chika0801** [comment]
> 有了，谢谢，原来这个客户端里还得开一下tunv6模式

如果你用singbox开tun，是有一些参数要调。

**Comment by ghost** [comment]
请问ipv6 dns服务器怎么配置

**Comment by chika0801** [comment]
> 不过我还有一个问题，IPV6解决了，但是好像没有IPV6的DNS服务器，如何添加，格式是什么，我看官方配置文件也没有ipv6dns服务器的示例

你实在要写v6的dns，地址那写v6地址就成了

**Comment by ghost** [comment]
cloudflare的ipv6 dns

**Comment by ghost** [comment]
我是想双栈dns，v4dns ＋v6 dns

**Comment by chika0801** [comment]
> > > 我是Windows11系统，Nekobox客户端，sing-box核心，tun模式，服务器是debian12.2
> > 
> > 
> > 建议你去nekobox的tg群问下
> 
> 我在客户端的github提问了，我没有tg号，收不到验证码

谷歌搜接码平台注册，或搜giffgaff买张英国实体卡注册，或86注册也可以试试

**Comment by chika0801** [comment]
我这只售后用我的配置示例
https://github.com/chika0801/sing-box-examples/tree/main/Tun

的解答。

你用其它客户端程序，我不负责售后，请咨询对应地方

**Comment by ghost** [comment]
我有接吗平台，但是只支持USDT或者别的虚拟币支付，我就懒得弄了，反正不怎么用，我记得bian可以支付宝买usdt

**Comment by ghost** [comment]
他有dns泄露，怎么办
![1](https://github.com/chika0801/hysteria-install/assets/138294823/dfb7d952-3e69-4129-8bcd-fd0a379b9786)

**Comment by chika0801** [comment]
> 我是想双栈dns，v4dns ＋v6 dns

没必要，你基本遇不到dns网站坏的时候

**Comment by ghost** [comment]
DNS泄露怎么办，这个很严重的

**Comment by chika0801** [comment]
你用我的配置我保你不露，这是几句话解释不清楚的，另外建议你不很懂工作原理，不要在意dns泄露问题，**它不是你vps被封什么的原因**

**Comment by ghost** [comment]
DNS泄露的话运营商不就知道你访问了什么网站了吗

**Comment by chika0801** [comment]
> DNS泄露的话运营商不就知道你访问了什么网站了吗

是的

> **不要在意dns泄露问题，它不是你vps被封什么的原因**

这是原因

**Comment by chika0801** [comment]
> 我有接吗平台，但是只支持USDT或者别的虚拟币支付，我就懒得弄了，反正不怎么用，我记得bian可以支付宝买usdt

https://5sim.net/zh

https://sms-activate.org/cn

推荐你这2个，我都用过

**Comment by ghost** [comment]
算了，不用这个了，这个测速很快，实际上看视频就1万多（手机浏览器），我还是等什么时候推出真正的vpn再说吧，代理再怎么魔改速度也上不去

**Comment by chika0801** [comment]
> 算了，不用这个了，这个测速很快，实际上看视频就1万多（手机浏览器），我还是等什么时候推出真正的vpn再说吧，代理再怎么魔改速度也上不去

建议你要么办联通，要么不想换运营商，加钱买其它商家的VPS

**Comment by ghost** [comment]
> > 算了，不用这个了，这个测速很快，实际上看视频就1万多（手机浏览器），我还是等什么时候推出真正的vpn再说吧，代理再怎么魔改速度也上不去
> 
> 建议你要么办联通，要么不想换运营商，加钱买其它商家的VPS

我是移动

**Comment by chika0801** [comment]
移动买年付200-300的HK CMI回程线路是最好（性价比）的

**Comment by ghost** [comment]
> 移动买年付200-300的HK CMI回程线路是最好（性价比）的

我碰到个很离谱的问题，openvpn，不管是tcp还是udp模式，下载文件只有3mbps，github或者apkpure，但是speedtest很快，单线程和多线程一样，不知道是啥问题，好像就这几天开始的，3台服务器都这样，香港阿里云，香港hostyun，东京直连

**Comment by ghost** [comment]
换了端口也没用，换了运营商测试也是一样的

**Comment by chika0801** [comment]
我不用openvpn帮不上你。
