### ISSUE TITLE
配置文件里的疑问

### ISSUE THREAD

**Issue by toyo2333** [chika0801/hysteria-install#7]
`listen: :443

tls:
  cert: /root/fullchain.cer
  key: /root/private.key

auth:
  type: password
  password: chika

resolver:
  type: https
  https:
    addr: 1.1.1.1:443
    timeout: 10s

acl:
  inline: 
    - reject(all, udp/443)`
1、这里 证书cer和key文件怎么制作获取呢？
2、规则里为什么拒绝所有udp443呢？这个协议不是监听udp443么？拒绝了怎么用呢?

**Comment by chika0801** [comment]
> 1、这里 证书cer和key文件怎么制作获取呢？

https://github.com/chika0801/Xray-install/blob/main/acme.md

https://github.com/chika0801/Xray-install/blob/main/certbot.md

可参考这2个。或自己搜索关键词申请免费SSL证书。

> 2、规则里为什么拒绝所有udp443呢？这个协议不是监听udp443么？拒绝了怎么用呢?

拒绝的是客户端发起的请求，和服务端对外监听UDP443无关。原因见：https://v2.hysteria.network/zh/docs/misc/About-HTTP3/ 当然你可以不用这条，纯个人喜好。

**Comment by toyo2333** [comment]
我目前Xray偷自己的证书，可以copy出来给这个用么？然后就是这个可以和xray共存么？我xray用的是443

**Comment by chika0801** [comment]
一份ssl证书你可以在任意vps上用。
只要它们是在有效期内且是有效的。

可以，xray监听的是tcp443，hy它们是监听udp的443，不会冲突。

**Comment by toyo2333** [comment]
> 一份ssl证书你可以在任意vps上用。
> 
> 只要它们是在有效期内且是有效的。
> 
> 
> 
> 可以，xray监听的是tcp443，hy它们是监听udp的443，不会冲突。

谢谢，已经弄好了。使用的docker。以及歇斯底里服务端自带的acme 。挺方便。
